### Playbook default settings
node: "awx"
compose_dir: "/opt"
awx_compose_dir: "{{ compose_dir }}/awx"
postgres_compose_dir: "{{ compose_dir }}/postgres"
external_database: "yes"

### Docker default settings
docker_registry: "dockerhost"
docker_registry_namespace: "docker-repo/awx"
awx_web_image: "awx_web"
awx_task_image: "awx_task"
awx_web_docker_actual_image: "{{ docker_registry }}/{{ docker_registry_namespace }}/{{ awx_web_image }}:{{ awx_version }}"
awx_task_docker_actual_image: "{{ docker_registry }}/{{ docker_registry_namespace }}/{{ awx_task_image }}:{{ awx_version }}"
docker_network_name: "awx"

### AWX Default Settings
admin_user: "admin"
admin_password: "{{ admin_password }}"
awx_secret_key: "awxsecret"
awx_host: "set_awx_fqdn"

### Postgres DB details
pg_version: "11"
pg_hostname: "set_database_hostname"
pg_password: "awxpass"
pg_port: "5432"
pg_username: "awx"
pg_database: "awx"
